server:
  port: 0
spring:
  application:
    name: kafka-streams-consumer-spring

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      client-id: kafka-consumer-client-id-01
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-commit-interval: 1000
      auto-offset-reset: earliest
    streams:
      application-id: kafka-consumer-application-id-01

